name: booktes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0-274.0.dev <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dio: ">=4.0.0 <5.0.0"
  flutter:
    sdk: flutter
  flutter_config: ^2.0.2
  get: 4.6.6
  openapi:
    path: api
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
